version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=employee_db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # Les scripts qui se trouvent dans ocker-entrypoint-initdb.d sont lancés au premier lancement du serveur de base de données Postgresl
          # Creation de la table employee
          - ./sql/create_employee_table.sql:/docker-entrypoint-initdb.d/create_employee_table.sql
          # remplissage de la table employee
          - ./sql/insert_employees.sql:/docker-entrypoint-initdb.d/insert_employees.sql
